[httpserver]
address = "0.0.0.0:8080"

[grpcserver]
address = "0.0.0.0:9090"

[database]
storage = "sql"

[logger]
level = "debug"
encoding = "json"
outputPaths = ["stdout"]
errorOutputPaths = ["stderr"]
