[httpserver]
address = "0.0.0.0:8080"

[grpcserver]
address = "0.0.0.0:9090"

[database]
storage = "sql"

[logger]
level = "debug"
encoding = "json"
outputPaths = ["stdout"]
errorOutputPaths = ["stderr"]

[rabbitmq]
url = "amqp://guest:guest@rabbitmq:5672/"
queueName = "calendar_queue"

[sender]
interval = 10

[email]
smtpServer = "mailhog"
smtpPort = 1025
username = ""
password = ""
from = "no-reply@example.com"
useTLS = false
insecureSkipVerify = true

[scheduler]
interval = 10
